//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

    
namespace FFeat.Note.Model
{
    [Serializable]
    public partial class NoteInfo
    {
        public int Id { get; set; }
        public string NoteName { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public string SubContent { get; set; }
        public int NoteType { get; set; }
        public int UserInfoId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
