//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FFeat.Note.IBll;
using FFeat.Note.IDal;
using FFeat.Note.Model;
using System;
using System.Collections.Generic;

namespace FFeat.Note.Bll
{
    public partial class UserInfoService:BaseService<UserInfo>,IUserInfoService
    {
    		public UserInfoService(IDbSession DbSession) : base(DbSession)
            {
            }
            public override void SetCurrentDal()
            {
                CurrentDal = this.DbSession.IUserInfoDal;
            }
    }
}
