 //------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;

namespace FFeat.Note.IDal
{
     public partial interface IDbSession
     {
    	
         	 IActionInfoDal IActionInfoDal { get; }
    		 INoteInfoDal INoteInfoDal { get; }
    		 IR_UsreInfo_ActionInfoDal IR_UsreInfo_ActionInfoDal { get; }
    		 IRoleInfoDal IRoleInfoDal { get; }
    		 IUserInfoDal IUserInfoDal { get; }
    	    
    
    }
    
}
