 //------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using FFeat.Note.IDal;
using System;
using System.Collections.Generic;

namespace FFeat.Note.Factory
{
        public partial class StaticDalFactory
        {
    	public static string  AssemblyName = System.Configuration.ConfigurationManager.AppSettings["DALAssemblyName"];
             public static IActionInfoDal GetActionInfoDal()=> Assembly.Load(AssemblyName).CreateInstance(AssemblyName + ".ActionInfoDal") as IActionInfoDal;
    	    public static INoteInfoDal GetNoteInfoDal()=> Assembly.Load(AssemblyName).CreateInstance(AssemblyName + ".NoteInfoDal") as INoteInfoDal;
    	    public static IR_UsreInfo_ActionInfoDal GetR_UsreInfo_ActionInfoDal()=> Assembly.Load(AssemblyName).CreateInstance(AssemblyName + ".R_UsreInfo_ActionInfoDal") as IR_UsreInfo_ActionInfoDal;
    	    public static IRoleInfoDal GetRoleInfoDal()=> Assembly.Load(AssemblyName).CreateInstance(AssemblyName + ".RoleInfoDal") as IRoleInfoDal;
    	    public static IUserInfoDal GetUserInfoDal()=> Assembly.Load(AssemblyName).CreateInstance(AssemblyName + ".UserInfoDal") as IUserInfoDal;
    	    
    
    }
    
}
